# Generated by Django 4.2.30 on 2026-06-13 03:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('semestre_ingresso', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Ingresso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('sigla', models.CharField(max_length=20, unique=True, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulação')),
                ('registro_funcional', models.CharField(blank=True, max_length=30, null=True, verbose_name='Registro Funcional')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Projeto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tema', models.CharField(choices=[('ODS_4', 'ODS 4 - Educação de Qualidade'), ('ODS_7', 'ODS 7 - Energia Limpa'), ('ODS_10', 'ODS 10 - Redução de Desigualdades'), ('ODS_11', 'ODS 11 - Cidades Sustentáveis'), ('ODS_12', 'ODS 12 - Consumo Responsável'), ('ODS_13', 'ODS 13 - Ação Contra a Mudança Global do Clima'), ('ESG_AMB', 'ESG - Ambiental'), ('ESG_SOC', 'ESG - Social'), ('ESG_GOV', 'ESG - Governança')], max_length=10, verbose_name='Tema (ESG/ODS)')),
                ('tecnologias', models.CharField(blank=True, help_text='Separadas por vírgula. Ex: React, Node.js, PostgreSQL', max_length=500, null=True, verbose_name='Tecnologias Utilizadas')),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano')),
                ('status_projeto', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_avaliacao', 'Aguardando Avaliação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=25, verbose_name='Status')),
                ('arquivo_url', models.CharField(blank=True, help_text='Path relativo ou URL absoluta (PDF, ZIP, link externo).', max_length=500, null=True, verbose_name='URL do Arquivo')),
                ('visivel_portfolio', models.BooleanField(default=False, help_text='Ativado automaticamente ao aprovar (RF06). Controla visibilidade na tela Explorar para todos os alunos e na tela Portfólio do dono do projeto.', verbose_name='Visível no Portfólio / Explorar')),
                ('visualizacoes', models.PositiveIntegerField(default=0, help_text='Incrementado a cada acesso à página do projeto em Explorar.', verbose_name='Visualizações')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Submissão')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Avaliação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projetos', to='projetos.aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projetos', to='projetos.curso', verbose_name='Curso')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_orientados', to='projetos.professor', verbose_name='Professor Orientador')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projeto',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
