# Generated by Django 4.2.30 on 2026-06-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='projetos.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['status_projeto', 'curso'], name='idx_projeto_status_curso'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['aluno', 'status_projeto'], name='idx_projeto_aluno_status'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['visivel_portfolio', '-visualizacoes'], name='idx_projeto_explorar'),
        ),
    ]
