# Generated by Django 4.2.30 on 2026-06-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Recife, PE', max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, help_text='Usado no perfil do Administrador', max_length=100, null=True, verbose_name='Setor / Departamento'),
        ),
    ]
